### ISSUE TITLE
Getting a "cURL Error: Failed sending HTTP request: Header overflow in" error with 6000+products

### ISSUE THREAD

**Issue by PalmaSolutions** [jmarreros/Update-inventory-WooCommerce#1]
When I execute the script I am getting this error on PHP 7.4 and Nginx with FPM and 6000+ products:
```
2020/10/02 21:26:14 [error] 24685#24685: *2 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: cURL Error: Failed sending HTTP request: Header overflow in /data/xxx/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:417
Stack trace:
#0 /data/xxx/vendor/automattic/woocommerce/src/WooCommerce/Client.php(82): Automattic\WooCommerce\HttpClient\HttpClient->request()
#1 /data/xxx/api.php(49): Automattic\WooCommerce\Client->get()
#2 {main}
  thrown in /data/xxx/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php on line 417" while reading response header from upstream, client: 192.000.000.00 server: localhost, request: "GET /api.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "localhost"
```
Not sure where it comes from, but it seems to be a buffering issue no?

**Comment by danielriveraayala** [comment]
Try ->['version' => 'wc/v3', 'verify_ssl' => false, 'timeout' => 20000] 
`$woocommerce = new Client(
    $url_API_woo,
    $ck_API_woo,
    $cs_API_woo,
    ['version' => 'wc/v3', 'verify_ssl' => false, 'timeout' => 20000]
);`

**Comment by jmarreros** [comment]
Try to sync less products, try with 10 for example.
If you want more products you have to make a batch logic

**Comment by danielriveraayala** [comment]
It is precisely what I did, the update to your code in batches of N in N products I have it in my fork of your repository
